spring.application.name=dev-clicker
spring.datasource.url=jdbc:postgresql://localhost:5432/devclicker
spring.datasource.username=siri
spring.datasource.password=siricarangueijo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
