spring.application.name=dev-clicker
spring.datasource.url=jdbc:postgresql://localhost:5432/devclicker
spring.datasource.username=devclicker_user
spring.datasource.password=devclicker_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
